permalink: pretty
baseurl: ""
shared_baseurl: ""
exclude:
  - docs
  - README.md
  - Gemfile
  - Gemfile.lock
  - build.sh
  - v*/nav.yml
  - vendor

markdown: redcarpet

kramdown:
  input: GFM

redcarpet:
  extensions:
    - autolink
    - highlighter
    - no_intra_emphasis
    - tables
    - prettify

gems:
  - jekyll-redirect-from
  - octopress-minify-html
