permalink: pretty
origin: "https://www.tinymce.com"
baseurl: ""
shared_baseurl: ""
syntax_highlight_theme: "tomorrow-night"
cdnurl: "https://cloud.tinymce.com/stable/tinymce.min.js"
codepen_url: "https://cloud.tinymce.com/5/tinymce.min.js?apiKey=qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc"
default_meta_keywords: tinymce, documentation, docs, plugins, customizable skins, configuration, examples, html, php, java, javascript, image editor, inline editor, distraction-free editor, classic editor

exclude:
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - wercker.yml
  - node_modules
  - .idea
  - .git

# redcarpet was messing up some of the codepens
markdown: kramdown

kramdown:
  syntax-highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'prettyprint'

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
