url: "https://www.tiny.cloud"
permalink: pretty
origin: "https://www.tiny.cloud"
baseurl: ""
shared_baseurl: ""
syntax_highlight_theme: "tomorrow-night"
cdnurl: "https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js"
tdcdnurl: "https://cdn.tiny.cloud/1/_your_api_key_/tinydrive/5-stable/tinydrive.min.js"
tinymce_live_demo_url: "https://cdn.tiny.cloud/1/qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc/tinymce/5-stable/tinymce.min.js"
tinydrive_live_demo_url: "https://cdn.tiny.cloud/1/qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc/tinydrive/5-stable/tinydrive.min.js"
webcomponent_url: "https://cdn.jsdelivr.net/npm/@tinymce/tinymce-webcomponent@1/dist/tinymce-webcomponent.min.js"
default_meta_keywords: tinymce, documentation, docs, plugins, customizable skins, configuration, examples, html, php, java, javascript, image editor, inline editor, distraction-free editor, classic editor, wysiwyg
# product variables
productname: TinyMCE
productmajorversion: 5
productminorversion: "5.10"
##### product name in codeblock
prodnamecode: tinymce
#### more names
companyname: Tiny
companynameformal: Tiny Technologies, Inc.
cloudname: Tiny Cloud
cloudfilemanager: Tiny Drive
enterpriseversion: TinyMCE Enterprise
communityname: TinyMCE Community
accountpage: Tiny Account
supportname: Tiny Support
betaprogram: Tiny Insights Program
#### some plugin names
prem_skins_icons: Tiny Skins and Icon Packs
#### Plan names
tieroneplan: Tiny Cloud Community Plan
tiertwoplan: Tiny Cloud Essential Plan
tierthreeplan: Tiny Cloud Professional Plan
enterpriseplan: Tiny Custom Plans
## common tiny.cloud URLs
supporturl: https://support.tiny.cloud
plugindirectory: https://www.tiny.cloud/tinymce/features/
gettiny: https://www.tiny.cloud/get-tiny
download-community: https://www.tiny.cloud/get-tiny/self-hosted/
download-enterprise: https://www.tiny.cloud/my-account/downloads/
accountpageurl: https://www.tiny.cloud/my-account
accountsignup: https://www.tiny.cloud/auth/signup/
pricingpage: https://www.tiny.cloud/pricing
contactpage: https://www.tiny.cloud/contact
legalpages: https://www.tiny.cloud/legal
communitysupporturl: https://stackoverflow.com/questions/tagged/tinymce
betaprogramurl: https://www.tiny.cloud/insights-program/
# HTML entities
tick: '&#10004;'
cross: '&#10006;'
nbsp: '&#160;'
tab: '&#160;&#160;'
newline: '<br>'
virt_ellps: '&#8942;'
ellps: '&#133;'

requires_5_1v: "> **Note**: This feature is only available for TinyMCE 5.1 and later."
requires_5_2v: "> **Note**: This feature is only available for TinyMCE 5.2 and later."
requires_5_3v: "> **Note**: This feature is only available for TinyMCE 5.3 and later."
requires_5_4v: "> **Note**: This feature is only available for TinyMCE 5.4 and later."
requires_5_5v: "> **Note**: This feature is only available for TinyMCE 5.5 and later."
requires_5_6v: "> **Note**: This feature is only available for TinyMCE 5.6 and later."
requires_5_7v: "> **Note**: This feature is only available for TinyMCE 5.7 and later."
requires_5_8v: "> **Note**: This feature is only available for TinyMCE 5.8 and later."
requires_5_9v: "> **Note**: This feature is only available for TinyMCE 5.9 and later."
requires_5_10v: "> **Note**: This feature is only available for TinyMCE 5.10 and later."

requires_jsscwar_230v: "> **Note**: This feature is only available for TinyMCE self-hosted server-side components, version 2.3.0 and later. To check the version of a running service, visit _&#60;domain&#62;_/_&#60;service&#62;_/version. Such as `http://localhost:8080/ephox-hyperlinking/version`."
requires_jsspelling_war_2_110_0v: "> **Note**: This feature is only available for the TinyMCE self-hosted spelling component, version 2.110.0 and later. To check the version of a running service, visit _&#60;domain&#62;_/_&#60;service&#62;_/version. Such as `http://localhost:8080/ephox-spelling/version`."
requires_jsspelling_war_2_118_0v: "> **Note**: This feature is only available for the TinyMCE self-hosted spelling component, version 2.118.0 and later. To check the version of a running service, visit _&#60;domain&#62;_/_&#60;service&#62;_/version. Such as `http://localhost:8080/ephox-spelling/version`."
ctrl_right_click: "> **Note**: When the TinyMCE context menu is _enabled_, users can still access the browser context menu, including the browser spellchecker, using the `Ctrl+Right click` shortcut. However if the `contextmenu_never_use_native` option is enabled, holding the `Ctrl` key will have no effect."
notonmobile: "> **Note**: This option is not supported on mobile devices."
premiumplugin: "> **Note**: This plugin is only available for [paid TinyMCE subscriptions](https://www.tiny.cloud/pricing)."
differs_for_mobile: "> **Note**: The default option for this setting is different for mobile devices. For information on the default mobile setting, see: [TinyMCE Mobile - Configuration settings with mobile defaults](https://www.tiny.cloud/docs/mobile/#mobiledefaultsforselectedsettings)."
releasenotes_for_stable: "> **Note**: This is the Tiny Cloud and TinyMCE Enterprise release notes. For information on the latest community version of TinyMCE, see: [TinyMCE Changelog](https://www.tiny.cloud/docs/changelog/)."
thirdPartyInteg: "> **Important**: This Integration is maintained by a third-party developer. Tiny Technologies, Inc. bears no responsibility for this integration, which is not covered by the Tiny Self-Hosted Software License Agreement. For issues related to the integration, contact the third-party project directly."

moxieMNotOnCloud: "> **Note**: The MoxieManager plugin is _not_ provided on the Tiny Cloud, and is provided as a self-hosted solution only."

svgsNotSupported: "> **Note**: SVGs (Scalable Vector Graphics) are not supported in TinyMCE to protect our users and their end-users. SVGs can be used to perform both client-side and server-side attacks."

predefinedIconsOnly: "Name of the icon to be displayed. Must correspond to an icon: in the [icon pack](https://www.tiny.cloud/docs/advanced/editor-icon-identifiers/), in a [custom icon pack](https://www.tiny.cloud/docs/advanced/creating-an-icon-pack/), or added using the [`addIcon` API](https://www.tiny.cloud/docs/api/tinymce.editor.ui/tinymce.editor.ui.registry/#addicon)."

liveDemoIframeCSSStyles: "'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }'"

logoForDemos: "https://www.tiny.cloud/docs/images/logos/android-chrome-256x256.png"
logoForDemosHTML: "<p><img style=\"display: block; margin-left: auto; margin-right: auto;\" title=\"Tiny Logo\" src=\"https://www.tiny.cloud/docs/images/logos/android-chrome-256x256.png\" alt=\"TinyMCE Logo\" width=\"128\" height=\"128\" /></p>"
logoForDemosHTMLRight: "<p><img style=\"float: right;\" title=\"Tiny Logo\" src=\"https://www.tiny.cloud/docs/images/logos/android-chrome-256x256.png\" alt=\"TinyMCE Logo\" width=\"128\" height=\"128\" /></p>"

primaryColor: "#1976D2"

exclude:
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - wercker.yml
  - node_modules
  - .idea
  - .git
  - .github
  - _new_content_templates
  - nixpin.nix
  - shell.nix
  - Makefile

# redcarpet was messing up some of the live demos
markdown: kramdown

kramdown:
  syntax-highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'prettyprint'

plugins:
  - jekyll-last-modified-at
  - jekyll-redirect-from
  - jekyll-sitemap
