url: "https://www.tiny.cloud"
permalink: pretty
origin: "https://www.tiny.cloud"
baseurl: ""
shared_baseurl: ""
syntax_highlight_theme: "tomorrow-night"
cdnurl: "https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js"
tinymce_codepen_url: "https://cdn.tiny.cloud/1/qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc/tinymce/5/tinymce.min.js"
tinydrive_codepen_url: "https://cdn.tiny.cloud/1/qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc/tinydrive/stable/tinydrive.min.js"
default_meta_keywords: tinymce, documentation, docs, plugins, customizable skins, configuration, examples, html, php, java, javascript, image editor, inline editor, distraction-free editor, classic editor
# product variables
productname: TinyMCE
productmajorversion: 5
productminorversion: 5.4
##### product name in codeblock
prodnamecode: tinymce
companyname: Tiny
companynameformal: Tiny Technologies, Inc.
cloudname: Tiny Cloud
cloudfilemanager: Tiny Drive
enterpriseversion: TinyMCE Enterprise
accountpage: Tiny Account
supportname: Tiny Support
#### Plan names
tieroneplan: Tiny Cloud Community Plan
tiertwoplan: Tiny Cloud Essential Plan
tierthreeplan: Tiny Cloud Professional Plan
enterpriseplan: Tiny Custom Plans
## common tiny.cloud URLs
supporturl: https://support.tiny.cloud
plugindirectory: https://www.tiny.cloud/apps/
gettiny: https://www.tiny.cloud/get-tiny
accountpageurl: https://apps.tiny.cloud/my-account
accountsignup: https://www.tiny.cloud/auth/signup
productpages: https://apps.tiny.cloud/products
pricingpage: https://www.tiny.cloud/pricing
contactpage: https://www.tiny.cloud/contact
# HMTL entities
tick: '&#10004;'
cross: '&#10006;'
nbsp: '&#160;'
tab: '&#160;&#160;'
newline: '<br>'
virt_ellps: '&#8942;'
ellps: '&#133;'

requires_5_1v: "> **Note**: This feature is only available for TinyMCE 5.1 and later."
requires_5_2v: "> **Note**: This feature is only available for TinyMCE 5.2 and later."
requires_5_3v: "> **Note**: This feature is only available for TinyMCE 5.3 and later."

requires_jsscwar_230v: "> **Note**: This feature is only available for TinyMCE self-hosted server-side components, version 2.3.0 and later. To check the version of a running service, visit _&#60;domain&#62;_/_&#60;service&#62;_/version. Such as `http://localhost:8080/ephox-hyperlinking/version`."

notonmobile: "> **Note**: This option is not supported on mobile devices."
premiumplugin: "> **Note**: This plugin is only available for [paid TinyMCE subscriptions](https://www.tiny.cloud/pricing)."
differs_for_mobile: "> **Note**: The default option for this setting is different for mobile devices. For information on the default mobile setting, see: [TinyMCE Mobile - Configuration settings with mobile defaults](https://www.tiny.cloud/docs/mobile/#mobiledefaultsforselectedsettings)."

thirdPartyInteg: "> **Important**: This Integration is maintained by a third-party developer. Tiny Technologies, Inc. bears no responsibility for this integration, which is not covered by the Tiny Self-Hosted Software License Agreement. For issues related to the integration, contact the third-party project directly."

moxieMNotOnCloud: "> **Note**: The MoxieManager plugin is _not_ provided on the Tiny Cloud, and is provided as a self-hosted solution only."

exclude:
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - wercker.yml
  - node_modules
  - .idea
  - .git

# redcarpet was messing up some of the codepens
markdown: kramdown

kramdown:
  syntax-highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'prettyprint'

plugins:
  - jekyll-last-modified-at
  - jekyll-redirect-from
  - jekyll-sitemap

