site:
  title: TinyMCE 4 Documentation
  url: https://tiny.cloud/docs
  start_page: tinymce::index.adoc
content:
  sources:
  - url: ./
    branches: HEAD
    start_path: ./
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
