name: Release > Tiny docs 6.0

on:
  workflow_dispatch:
  push:
    paths:
      - '**'
    branches:
      - 'release/docs-6'

jobs:
  build:
    name: Build Docs and Deploy
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [14]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        cache: 'yarn'
        node-version: ${{ matrix.node-version }}

    - name: (Release - Docs 6.0) Install dependencies
      run: yarn install

    - name: (Release - Docs 6.0) Build API References
      run: yarn build

    - name: (Release - Docs 6.0) Build Website
      run: yarn antora ./antora-playbook-production.yml

    - name: (Release - Docs 6.0) Rename sitemap.xml (Temporary solution - Amit)
      shell: bash
      run: |
        mv ./build/site/sitemap.xml ./build/site/antora-sitemap.xml

    - name: (deploy) Upload to S3
      run: aws s3 sync --acl=public-read --delete ./build/site s3://tiny-cloud-antora-docs-production/docs
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY }}

    - name: (deploy) Invalidate Cache
      run: aws cloudfront create-invalidation --distribution-id E3LFU502SQ5UR --paths "/docs/*"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY }}
